site_name: APL MOOC
theme:
  name: material
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - nagivation.top  
    - navigation.sections
markdown_extensions:
  - md_in_html
extra_css:
  - styles/main.css
extra_javascript:
  - js/mooc.js
  - js/languagebar.js
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
nav:
  - Home: index.md
  - Course:
    - 0 - The wonderful world of APL:
      - 0.1 - Quirky and different: course/ch0/part1.md
      - 0.2 - What's the big idea?: course/ch0/part2.md
      - 0.3 - Useful resources: course/ch0/part3.md
    - 1 - Getting your toes wet:
      - 1.1 - Immediate execution mode: course/ch1/part1.md
      - 1.R - Read exercises: course/ch1/read.md
      - 1.W - Write exercises: course/ch1/write.md
  - Receiving ECTS Credits: credits.md
  - Log in: login.md
