site_name: APL MOOC
theme:
  name: material
  logo: course/assets/apl.svg
  favicon: course/assets/favicon.svg
  palette:
    - scheme: default
      primary: purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - nagivation.top  
    - content.code.annotate
  font:
    code: APL385
markdown_extensions:
  - md_in_html
extra_css:
  - styles/main.css
extra_javascript:
  - js/mooc.js
  - js/languagebar.js
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - Home: index.md
  - Course:
    - 0 - The wonderful world of APL:
      - 0.1 - Quirky and different: course/ch0/part1.md
      - 0.2 - What's the big idea?: course/ch0/part2.md
      - 0.3 - Useful resources: course/ch0/part3.md
      - 0.4 - About the course: course/ch0/part4.md
    - 1 - Getting your toes wet:
      - 1.1 - Immediate execution mode: course/ch1/part1.md
      - 1.2 - Basic operations and input: course/ch1/part2.md
      - 1.3 - How do I type these characters?!?!?!?: course/ch1/part3.md
      - 1.4 - Order of execution: course/ch1/part4.md
      - 1.5 - When things go wrong: course/ch1/part5.md
      - 1.S - Summary: course/ch1/summary.md
      - 1.R - Read exercises: course/ch1/read.md
      - 1.W - Write exercises: course/ch1/write.md
    - 2 - Variables, functions, system:
      - 2.1 - Assignment: course/ch2/part1.md
      - 2.2 - Higher dimensional space: course/ch2/part2.md
      - 2.3 - Arithmetic operations on vectors: course/ch2/part3.md
      - 2.4 - Nested arrays: course/ch2/part4.md
      - 2.5 - A Musical Interlude: course/ch2/part5.md
      - 2.S - Summary: course/ch2/summary.md
      - 2.R - Read exercises: course/ch2/read.md
      - 2.W - Write exercises: course/ch2/write.md
  - Receiving ECTS Credits: credits.md
  - Log in: login.md
